# Nome do fluxo de trabalho que aparecerá na aba "Actions"
name: Deploy para GitHub Pages

# Define quando o fluxo será acionado: ao fazer push na branch "main"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Permite disparar manualmente também

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
